#
# First responder duty, powered by imjohnbo/issue-bot
#
name: First Responder
on:
  workflow_dispatch:
  #schedule:
  # First of every month – https://crontab.guru
  #- cron: 0 0 1 * *

jobs:
  first_responder:
    name: New responder duty
    runs-on: ubuntu-latest
    steps:
    
    - name: Set env number
      run: |
        echo "iNum={{ previousIssueNumber }}" >> "$GITHUB_ENV"
    - name: Set env data
      id: propdata
      run: |
        echo "::set-output name=data::$(curl -s https://api.github.com/repos/CC-Treasury/issueblog/issues/26 | jq '.body' | sed 's/\"//g')"
    - name: Set env body
      run: |
        echo "iBody=${{ steps.propdata.outputs.data }}" >> "$GITHUB_ENV"

    - name: Get template
      uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/first_responder.md # assignees, labels, and title defined in issue template header
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Prepare issue Message
      id: issue-message-creator
      run: |
        MY_STRING=$(cat<<'EOF'
        ${{ env.iBody }}
        EOF)
        echo "MY_STRING<<EOF" >> $GITHUB_ENV
        echo "$MY_STRING" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    # Generates and pins new first responder issue, closes previous, writes linking comments, assigns to next person in line, adds to organization project number 550, column name "Duties", milestone number 10
    - name: Todays date
      run: echo "TODAY=$(date -d '7 days' '+ %A, %dth %B, %Y')" >> $GITHUB_ENV
    - name: New first responder issue
      uses: imjohnbo/issue-bot@v3
      with:
        token: ${{ secrets.PAT }} # Built in GITHUB_TOKEN permissions are too restrictive, so a personal access token is used here
        assignees: ${{ steps.extract.outputs.assignees }}
        labels: ${{ steps.extract.outputs.labels }}
        title: Treasury Advisory Service Meeting - ${{ env.TODAY }}
        body: "${{ env.MY_STRING }} https://github.com//CC-Treasury/issueblog/issues/${{ env.iNum }}"
          
        project: 1  # The project-number from organization project https://github.com/orgs/org/projects/project-number
        column: In progress
        pinned: false
        close-previous: true
        linked-comments: true
