name: Weekly Report
on:
  workflow_dispatch:
  schedule:
    - cron: '20 * * * *' # At 06:00 on Sunday
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
